/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoriaStoryIdRouteImport } from './routes/historia.$storyId'
import { Route as HistoriaStoryIdBibliaRouteImport } from './routes/historia.$storyId.biblia'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaStoryIdRoute = HistoriaStoryIdRouteImport.update({
  id: '/historia/$storyId',
  path: '/historia/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaStoryIdBibliaRoute = HistoriaStoryIdBibliaRouteImport.update({
  id: '/biblia',
  path: '/biblia',
  getParentRoute: () => HistoriaStoryIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/historia/$storyId': typeof HistoriaStoryIdRouteWithChildren
  '/historia/$storyId/biblia': typeof HistoriaStoryIdBibliaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/historia/$storyId': typeof HistoriaStoryIdRouteWithChildren
  '/historia/$storyId/biblia': typeof HistoriaStoryIdBibliaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/historia/$storyId': typeof HistoriaStoryIdRouteWithChildren
  '/historia/$storyId/biblia': typeof HistoriaStoryIdBibliaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/login'
    | '/signup'
    | '/historia/$storyId'
    | '/historia/$storyId/biblia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/login'
    | '/signup'
    | '/historia/$storyId'
    | '/historia/$storyId/biblia'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/login'
    | '/signup'
    | '/historia/$storyId'
    | '/historia/$storyId/biblia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  HistoriaStoryIdRoute: typeof HistoriaStoryIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia/$storyId': {
      id: '/historia/$storyId'
      path: '/historia/$storyId'
      fullPath: '/historia/$storyId'
      preLoaderRoute: typeof HistoriaStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia/$storyId/biblia': {
      id: '/historia/$storyId/biblia'
      path: '/biblia'
      fullPath: '/historia/$storyId/biblia'
      preLoaderRoute: typeof HistoriaStoryIdBibliaRouteImport
      parentRoute: typeof HistoriaStoryIdRoute
    }
  }
}

interface HistoriaStoryIdRouteChildren {
  HistoriaStoryIdBibliaRoute: typeof HistoriaStoryIdBibliaRoute
}

const HistoriaStoryIdRouteChildren: HistoriaStoryIdRouteChildren = {
  HistoriaStoryIdBibliaRoute: HistoriaStoryIdBibliaRoute,
}

const HistoriaStoryIdRouteWithChildren = HistoriaStoryIdRoute._addFileChildren(
  HistoriaStoryIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  HistoriaStoryIdRoute: HistoriaStoryIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
